(function() {var implementors = {};
implementors["nbez"] = ["impl&lt;F:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> + <a class='trait' href='nbez/trait.Float.html' title='nbez::Float'>Float</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='nbez/struct.Point2d.html' title='nbez::Point2d'>Point2d</a>&lt;F&gt;","impl&lt;F:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> + <a class='trait' href='nbez/trait.Float.html' title='nbez::Float'>Float</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='nbez/struct.Vector2d.html' title='nbez::Vector2d'>Vector2d</a>&lt;F&gt;","impl&lt;F:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> + <a class='trait' href='nbez/trait.Float.html' title='nbez::Float'>Float</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='nbez/struct.Point3d.html' title='nbez::Point3d'>Point3d</a>&lt;F&gt;","impl&lt;F:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> + <a class='trait' href='nbez/trait.Float.html' title='nbez::Float'>Float</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='nbez/struct.Vector3d.html' title='nbez::Vector3d'>Vector3d</a>&lt;F&gt;","impl&lt;F:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> + <a class='trait' href='nbez/trait.Float.html' title='nbez::Float'>Float</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='nbez/struct.Point4d.html' title='nbez::Point4d'>Point4d</a>&lt;F&gt;","impl&lt;F:&nbsp;<a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> + <a class='trait' href='nbez/trait.Float.html' title='nbez::Float'>Float</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html' title='core::cmp::Ord'>Ord</a> for <a class='struct' href='nbez/struct.Vector4d.html' title='nbez::Vector4d'>Vector4d</a>&lt;F&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
